-- ============================================================
-- Seed: Nederlandse hockeyclub registry (279 clubs)
-- Gegenereerd uit hockeyclubs_nederland.xlsx
-- Draai dit NA schema.sql en seed_pilot.sql
-- Geocoördinaten worden ingevuld zodra een club voor het eerst
-- gebruikt wordt (lazy geocoding via OpenRouteService).
-- ============================================================

INSERT INTO clubs_registry (name, address, verified)
VALUES
  ('Abcoude (HV)', 'Ruwelspad 3 1391 JA Abcoude', false),
  ('Alecto (L.S.C.)', 'Bloemerd 8 2353 BZ Leiderdorp', false),
  ('Alkmaarsche (M.H.C.)', 'Olympiaweg 12 1816 MJ Alkmaar', false),
  ('Alliance (M.H.C.)', 'Sportparklaan 8 2103 VT HEEMSTEDE', false),
  ('Almeerse (H.C.)', 'Klein Brandt Sportpark 4 1312 JW Almere', false),
  ('Almelo (M.H.C.)', 'Willem de Clercqstraat 97 7604 AR Almelo', false),
  ('Alphen (H.C.)', 'Olympiaweg 3 2406 LG Alphen a/d Rijn', false),
  ('Amersfoortse (M.H.C.)', 'Barchman Wuytierslaan 234 3819 AC Amersfoort', false),
  ('AMHC FIT', 'Vikingpad 41 1034 VG Amsterdam', false),
  ('Amstelveen (M.H.C.)', 'Startbaan 9 1185 XP Amstelveen', false),
  ('Amsterdamsche (H. & B.C.)', 'Nieuwe Kalfjeslaan 19 1182 AA Amstelveen', false),
  ('AMVJ (H.C.)', 'Aanloop 2 1183 SZ Amstelveen', false),
  ('Apeldoornsche (M.H.C.)', 'Sportpark Orderbos 29 7313 HN Apeldoorn', false),
  ('Apeliotes (N.S.H.C.)', 'Heyendaalseweg 141 6525 AJ Nijmegen', false),
  ('Ares (H.C.)', 'Malkenschoten 43 7333 NM Apeldoorn', false),
  ('Arnhemse (H.C.)', 'Beekhuizenseweg 95 6881 AH Velp', false),
  ('Arnhemse Antilope Vereniging', 'Gruttostraat 14 6883 CN Velp', false),
  ('Assen (H.V.A.)', 'Mien Ruijsweg 3 9408 KA Assen', false),
  ('Athena', 'Voorlandpad 13 1098 TZ Amsterdam', false),
  ('Avanti (W.M.H.C.)', 'Jaspersweg 11 7103 AV Winterswijk', false),
  ('Baarle, HC', 'Sportlaan 20 5111 BX Baarle-Nassau', false),
  ('Baarnse (M.H.V)', 'De Geerenweg 10 3741 RS Baarn', false),
  ('Bakel (G.H.V.)', 'Geneneind 4 a 5761 RH Bakel', false),
  ('Barendrecht (HCB)', 'Zuider Carnisseweg 101 2993 AZ Barendrecht', false),
  ('Barneveld (M.H.C.)', 'Wethouder Rebellaan 144 3771 KA BARNEVELD', false),
  ('Basko (V.M.H.C.)', 'De Korze 86 5504 MK Veldhoven', false),
  ('Bedum (H.C.)', 'Sportlaan 20 9781 CL Bedum', false),
  ('Bemmel 800 (M.H.C.)', 'Ressensestraat 30 C 6684 DA Bemmel', false),
  ('Bennebroek (M.H.C.)', 'Isaac Sweerslaan 2121 VN Bennebroek', false),
  ('Berkel en Rodenrijs (H.V.)', 'Het Hoge Land 31 2652 EA Berkel en Rodenrijs', false),
  ('Berkel Enschot (M.H.C.)', 'Generaal Eisenhouwerweg 11 5056 CR Berkel-Enschot', false),
  ('Berlicum (H.C.)', 'Groenstraat 14 5258 TH Berlicum', false),
  ('Best (M.H.C.)', 'Sportlaan 6 a 5683 CS Best', false),
  ('Beuningen (M.H.C.)', 'Ooigraaf 1 6641 TZ Beuningen', false),
  ('Bleiswijk (H.V.)', 'Merenweg 20 a 2665 KM Bleiswijk', false),
  ('Bloemendaal (H.C.)', 'Aelbertsbergweg 3 2061 AA Bloemendaal', false),
  ('Boekel (H.C.)', 'Waterval 1 5427 HL Boekel', false),
  ('Bommelerwaard (M.H.C.)', 'Van Heemstraweg West 29 5301 PZ Zaltbommel', false),
  ('Boxmeer (M.H.C.)', 'Sportlaan 3 5831 DA Boxmeer', false),
  ('BredaBurgemeester de', 'Manlaan 26 4837 BN Breda', false),
  ('Bredius Rollers', 'Kievietstraat 40 3443 BG Woerden', false),
  ('Buitenhout (M.H.C.)', 'Trekweg 71 1338 GA Almere', false),
  ('Bully (O.H.C.)', 'Sportlaan 12 7576 WV Oldenzaal', false),
  ('Cartouche (V.M.H.C.)', 'Van Ruysdaellaan 3 a 2264 TG LEIDSCHENDAM', false),
  ('Castricum (M.H.C.)', 'Van Haerlemlaan 31 (Sportpark 1901 JM Castricum', false),
  ('Catwyck (H.C.)', 'De Krom 1 H 2221 KJ Katwijk', false),
  ('CHT', 'Rijtseweg 1 5087 BJ Diessen', false),
  ('Civicum (C.M.H.C.)', 'Sportlaan 7 5431 AP Cuijk', false),
  ('Coevorden (M.H.C.)', 'Sportlaan 2 7742 BZ Coevorden', false),
  ('Concordia (R.H.C.)', 'Burgemeester Geuljanslaan 1 C 6041 NA Roermond', false),
  ('Craeyenhout (H.B.S.)', 'Daal en Bergselaan 1 B 2565 AB ''s-Gravenhage', false),
  ('Cranendonck (H.C.)', 'De Romrijten 8 6026 RD Maarheeze', false),
  ('Culemborgse (M.H.C.)', 'Middelcoopstraat 69 4102 CG Culemborg', false),
  ('Dalfsen (M.H.C.)', 'Gerner Es 7 a 7722 RX Dalfsen', false),
  ('Daring (M.H.C.)', 'Ontspanningslaan 1 b 9646 BM Veendam', false),
  ('Dash (M.H.C.)', 'Nieuweweg 6 e 9603 BM Hoogezand', false),
  ('DDHC (Den Dunc Hercules Combinatie H.C.)', 'Kloosterweg 4 4941 EG Raamdonksveer', false),
  ('De Pont', 'Hazelaarweg 100 3053 PM Rotterdam', false),
  ('De Tubanten', 'Beatrixstraat 79 7511 KP Enschede', false),
  ('Delta Venlo', 'Wittendijkweg 59 5912 PJ Venlo', false),
  ('Den Bosch', 'Oosterplasweg 35 5215 HT ''s-HERTOGENBOSCH', false),
  ('Derby (H.C.)', 'Middellijn 3 3335 KC Zwijndrecht', false),
  ('DES (M.H.C.)', 'Eikendijk 25 5171 RG Kaatsheuvel (Loon op Zand)', false),
  ('Deurne (M.H.C.)', 'Energiestraat 9 5753 RN Deurne', false),
  ('Deventer (H.V.)', 'Leo Halleweg 3 7425 NA Deventer', false),
  ('Dieren (M.H.C.)', 'Imboslaan 2 A 6952 JP DIEREN', false),
  ('Doetinchemsche (H.C.)', 'Stokhorstweg 5 - sc 7006 AG Doetinchem', false),
  ('Doing', 'Forelsloot 5 2724 CA Zoetermeer', false),
  ('Dommel, De (M.H.C.)', 'Zegenwerp 1 A 5271 NC Sint Michielsgestel', false),
  ('Don Quishoot (E.S.H.V.)', 'Onze Lieve Vrouwestraat 1 5612 AW Eindhoven', false),
  ('Doornse (H.C.)', 'Wijngaardsesteeg 1 b 3941 MB Doorn', false),
  ('Dopie (S.V.H.C.)', 'Mekelweg 8 2628 CD Delft', false),
  ('Dordrechtse (M.H.C.)', 'Schenkeldijk 11 3328 LA Dordrecht', false),
  ('Dorsteti (H.V.)', 'Lekdijk Oost 13 B 3961 MB Wijk bij Duurstede', false),
  ('Drienerlose (H.C.)', 'Oude Horstlindelaan 7500 AE Enschede', false),
  ('Drunen (M.H.C.)', 'Prins Hendrikstraat 80 5151 GB Drunen', false),
  ('Druten (H.C.)', 'De Gelenberg 10 6654 AZ Druten', false),
  ('DSHC (Delftsche Studenten H.C.)', 'Mekelweg 8 2628 CD Delft', false),
  ('DVS', 'Arembergstraat 14 A 5583 CD Waalre', false),
  ('Ede (M.H.C.)', 'Bosrand 17 6718 ZN Ede', false),
  ('Eelde (H.C.)', 'Hooiweg 196 B 9765 EM Paterswolde', false),
  ('Eemsmond (H.C.)', 'Zwet 36 B 9932 AB Delfzijl', false),
  ('Eemvallei (H.C.)', 'Caraïben 1 | Olympus 18 3825 ZN | Amersfoort', false),
  ('Eersel (H.C.)', 'Postelseweg 72 5521 RD Eersel', false),
  ('EHV Enschede', 'Geessinkweg 148 7544 RB Enschede', false),
  ('Eindhoven (H.C.)', 'Marathonloop 5 5624 MC Eindhoven', false),
  ('EMM''21Oud', 'Adeselaan 42 2375 XE Rijpwetering', false),
  ('Emmen (M.H.C.)', 'Ullevi 36 7825 SE Emmen', false),
  ('Etten Leur (H.C.)', 'Olympiade 51 4873 DA Etten-Leur', false),
  ('Evergreen (M.H.V.)', 'Dr. Albert Schweitzerdreef 431 3146 AP Maassluis', false),
  ('Feijenoord (H.C.)', 'Buitendijk 100 C 3078 XC Rotterdam', false),
  ('Fletiomare (M.H.C.)', 'Alendorperplaats 1 3454 NJ Utrecht', false),
  ('Flevoland Dronten (M.H.C.)', 'Educalaan 17 8251 GC Dronten', false),
  ('Forcial (M.H.V.)', 'Tweede slag 3 3235 CR Rockanje', false),
  ('Forescate (M.H.C.)', 'Weddeloop 1 2253 ST Voorschoten', false),
  ('GCHC (Gron. Cr. &Hockey Club)', 'Blauwborgje 26 a 9747 AC Groningen', false),
  ('Geel-Zwart (V.M.H.C.)', 'Middegaal 39 5461 XC Veghel', false),
  ('Geldermalsen (H.C.)', 'Randweg 5 4191 NN Geldermalsen', false),
  ('Geldrop (Hockey)', 'Gijzenrooiseweg 3 5661 MA Geldrop', false),
  ('Gemert (H.C.)', 'Sportlaan 12 5421 SK Gemert', false),
  ('GHBS (M.H.C.)', 'Laan Corpus den Hoorn 101 9728 JR Groningen', false),
  ('Gilze Rijen (H.C.)', 'Sportparkweg 9 5121 MP Rijen', false),
  ('Goeree Overflakkee (H.C.)', 'Oostplaatseweg 1 3241 LV Middelharnis', false),
  ('Goes (GMHC)', 'Geldeloozepad 5 i 4463 AJ Goes', false),
  ('Goirle (M.H.C.)', 'Schietberg 6 5051 NZ Goirle', false),
  ('Gooische (H.C.)', 'Meerweg 75 1405 BD BUSSUM', false),
  ('Goorse (M.H.C.)', 'Rubensstraat 2 7471 HX Goor', false),
  ('Gorssel/Epse (HC)', 'Hassinklaan 3 7214 AA Epse', false),
  ('Goudse (M.H.C.)', 'Groenhovenpark 4 2803 PH Gouda', false),
  ('GP Bulls', 'Strijdakker 1 5673 TN Nuenen', false),
  ('Graspiepers, de (DMHC)', 'Sportlaan 8 9203 NW Drachten', false),
  ('Grave (H.C.)', 'Stoottroepenweg 2 a 5364 MV Grave', false),
  ('Groen-Geel (H.C.C.)', 'Buurtweg 122 2244 AJ Wassenaar', false),
  ('GSHC (Gron. Stud. H.C.)', 'Blauwborgje 26 9747 AC Groningen', false),
  ('H.C. Diemen', 'Sportlaan 9 1111 PX Diemen', false),
  ('Haackey (H.H.C.)', 'Sportpark Groot Scholtenhagen Scholtenhagenweg 40 d 7481 VP Haaksbergen', false),
  ('Haarlem (H.C.)', 'Vergierdeweg 265 B 2026 BJ Haarlem', false),
  ('Haaskamp, DeBurgwal 8', '3958 ER Amerongen', false),
  ('Hardenberg (GZG)', 'Steenanjer 2 7773 GG Collendoorn (Hardenberg)', false),
  ('Harlinger Mixed Hockey Club', 'Westerzeedijk 13 8862 PK Harlingen', false),
  ('Hattemse M.H.C.', 'Hazenakker 2 8051 AT Hattem', false),
  ('HBS (MHC)', 'Bergweg 1 -a 2061 KB Bloemendaal', false),
  ('HC Dokkum', 'Tolhuispark 9103 SN Dokkum', false),
  ('HC Martinus', 'Eikenlaan 253 9741 EZ Groningen', false),
  ('HC SpireDe Weyver 7', '1718 MS Hoogwoud', false),
  ('HCAS (H.C. Asten-Someren)', 'Rootweg 3 5721 VK Asten', false),
  ('HCC', 'Capelseweg 33 2907 XA Capelle aan den IJssel', false),
  ('HCHN (Hellendoorn-Nijverdal)', 'Koersendijk 3 7443 PP Nijverdal', false),
  ('HCM', 'Drielsedijk 17 a 6803 ED Arnhem', false),
  ('HCOIJ (Oude IJsselstreek HC)', 'Industrieweg 2 7071 CK Ulft', false),
  ('HCSO', 'Manegelaan 3 9502 CB Stadskanaal', false),
  ('HCW (Winschoten)', 'St. Vitusholt 7e laan 8 9674 AX Winschoten', false),
  ('HDL (M.H.C. )', 'Steen en Stokstraat 1 5473 RN Heeswijk-Dinther', false),
  ('HDM (H.H.V. Haagsche Delftsche Mixed)', 'Theo Mann-Bouwmeesterlaan 205 2597 GV Den Haag', false),
  ('HDS (H.H.&C.C. Houdt Dapper Stand)', 'Madesteinweg 20 2553 EC Den Haag', false),
  ('Heerhugowaard (M.H.C.)', 'De Vork 7 1704 BX Heerhugowaard', false),
  ('Heesch (M.H.C.)', 'Schoonstraat 99 b 5384 AM Heesch', false),
  ('Heeze (Hockey)', 'Sterkselseweg 53 5591 VE Heeze', false),
  ('Helmond (H.C.)', 'Horst 27 5707 GW Helmond', false),
  ('Hermes (H.S.C.)Linieweg (sportpark)', '27 1783 BA Den Helder', false),
  ('HGC (HOC Gazellen Comb.)', 'Buurtweg 120 2244 AJ WASSENAAR', false),
  ('HIC (H.V.)', 'Escapade 7 1183 NM Amstelveen', false),
  ('Hilvarenbeek (H.C.)', 'Roodloop 1 5081 XZ Hilvarenbeek', false),
  ('Hilversumsche (M.H.C.)', '''t Jagerspaadje 24 1231 KJ Loosdrecht', false),
  ('HISALIS (H.C.)', 'Spekkelaan 1 2161 GH Lisse', false),
  ('Hockeer (H.V.)', 'Bemelerweg 85 6267 AL Cadier en Keer', false),
  ('Hockeyclub Groningen', 'Kerklaan 35 9751 NL Haren', false),
  ('HOCO (M.H.C.)', 'Sportlaan 10 5062 JK Oisterwijk', false),
  ('HOD (H.V.)', 'Pastoor Heerkensdreef 18 5552 BG Valkenswaard', false),
  ('Hoeksche Waard, De (H.C.)', 'Vrouwehuisjesweg 11 3271 LX Mijnsheerenland', false),
  ('Hoevelaken (M.H.C.)', 'Weidelaan 31 3871 PP Hoevelaken', false),
  ('Holten (H.C.)', 'Aaltinksweg 1 b 7451 DX Holten', false),
  ('Hondsrug, De (H.C.)', 'De Klencke 32 a 9472 RN Zuidlaren', false),
  ('Hoogeveen', 'Sportlaan 5 7902 NB Hoogeveen', false),
  ('Hoorn (WFHC)', 'Roskam 6 1689 VR Zwaag', false),
  ('Hopbel, De (S.M.H.C.)', 'Rooise Heide 18 5481 SG Schijndel', false),
  ('Horst (H.C.)', 'Gebr. v Doornelaan 126 5960 BE Horst', false),
  ('Houten (H.C.)', 'Groene Hoon 1 3991 LZ Houten', false),
  ('Hudito (D.H.C.)', 'Anthony Fokkerweg 2 2629 HC DELFT', false),
  ('Huizer H.C.Bestevaer 250', '1411 DT Naarden', false),
  ('Hurley (T.H.C.)', 'Nieuwe Kalfjeslaan 21 1182 AA Amstelveen', false),
  ('IJburg (AHC)', 'Jan Beijerpad 1 Diemerpar 1087 BX Amsterdam', false),
  ('IJssel, De (HC)', 'Sportpark Dorrestein 3 2912 TL Nieuwerkerk aan den IJssel', false),
  ('IJsseloever (H.C.)', 'Zomerdijk 42 3402 MJ IJsselstein', false),
  ('Kampen (H.C.)', 'Hilbert van Dijkstraat 3 8264 PC Kampen', false),
  ('Kampong (S.V.)', 'Laan van Maarschalkerweerd 14 3585 LJ Utrecht', false),
  ('Keistadrollers', 'Furglerplein 3 3815 KZ Amersfoort', false),
  ('Kieviten, DeDr.', 'Mansveltkade 11 2242 TZ Wassenaar', false),
  ('Kikkers, De (M.H.C.)', 'Fandango 19 2152 SJ Nieuw-Vennep', false),
  ('Klein Zwitserland (H.C.)', 'Klatteweg 113 2597 KA Den Haag', false),
  ('KNHB', 'Wattbaan 31 -49 3439 ML Nieuwegein', false),
  ('Kraaien, De (Z.H.C.)', 'Zuiderweg 68 a 1456 NH Wijdewormer', false),
  ('Krimpen (M.H.C.)', 'Driekamp 7 2924 AN Krimpen a/d IJssel', false),
  ('Kromhouters, De (T.H.C.C.)', 'Beethovenstraat 4003 KX Tiel', false),
  ('Kromme Rijn (H.C.)', 'Tolhuislaan 3 b 3981 HR Bunnik', false),
  ('Larensche (M.H.C.)', 'Eemnesserweg 33 a 1251 NB Laren', false),
  ('Leerdam (H.C.)', 'Bruininxdeelsekade 4 4143 LM Leerdam', false),
  ('Leeuwarden (M.H.C.)', 'Kalverdijkje 68 8924 JJ LEEUWARDEN', false),
  ('Leiden', 'Hofbrouckerlaan 51 a 2341 LM Oegstgeest', false),
  ('Leidse Hockeyclub Roomburgvan', 'Vollenhovenkade 20 2313 GG Leiden', false),
  ('Lelystad (M.H.C.)', 'Sportparkweg 3 8223 PB Lelystad', false),
  ('Lemmer (M.H.C.)', 'Straatweg 72 a 8531 PZ Lemmer', false),
  ('Leonidas (R.H.V.)', 'Toepad 95 3063 NJ Rotterdam', false),
  ('Leusden (M.H.C.)', 'Schammersteeg 2 3835 PT Leusden-Stoutenburg', false),
  ('Liberty (M.H.C.)', 'Alexanderstraat 3 5104 GV Dongen', false),
  ('Liempde (H.C.)', 'Hogenbergseweg 52 5298 TT Liempde', false),
  ('Lochemse (H.C.)', 'Koopsdijk 1 B 7241 RE Lochem', false),
  ('Loenense MHC', 'Rijksstraatweg 182 3632 AJ Loenen a/d Vecht', false),
  ('LosserTweelenbeecke 12', '7586 AB Sportpark ''t Wilpelo - Overdinkel', false),
  ('Maarn (M.H.C.)', 'Planetenbaan 1 3951 EH Maarn', false),
  ('Maarssen (MHV)', 'Oostwaard 32 3602 AA Maarssen', false),
  ('Maastrichtse HC', 'Sportpark Geusselt; Discusworp 10 6225 XP Maastricht', false),
  ('Madese (H.C.)', 'Schietberglaan 12 4921 VJ Made', false),
  ('Magnus (S.M.H.C.)', 'Wilgenlaan 1 C 1741 ZP Schagen', false),
  ('Meerssen (H.V.)', 'Heiveld 3 6241 EK Bunde', false),
  ('Meeuwen, De', 'Sportlaan 87 b 8302 AX Emmeloord', false),
  ('MEP (M.H.C.)', 'Molenwijk 1 a 5282 SH Boxtel', false),
  ('Meppeler (H.V.)', 'Koedijkslanden 12 7944 PA Meppel', false),
  ('Mezen, De (N.W.V.M.H.C.)', 'Parkweg 8 3842 AD HARDERWIJK', false),
  ('MHC de Westerduiven', 'Westsingel 33 6921 RX Duiven', false),
  ('MHC Epe', 'Wachtelenbergweg 13 8162 XC Epe', false),
  ('MHC', 'SteenwijkMiddenweg 14 8332 CZ Steenwijk', false),
  ('Mierlo (H.C.)', 'Oudvensestraat 9 5731 SH Mierlo', false),
  ('Mijdrecht (HV)', 'Proostdijstraat 41 3641 AT Mijdrecht', false),
  ('Mill (H.C.)', 'Langenboomseweg 5 5451 JH Mill', false),
  ('Mistral (H.C.)', 'Baanvelden 11 C 4715 RH Rucphen', false),
  ('Montfoort (H.C.)', 'Bovenkerkweg 14 3417 TA Montfoort', false),
  ('MOP (V.M.H.&C.C.)', 'Sportpark ''Bergenshuizen'' De Bus 2 5262 LV Vught', false),
  ('Muiderberg (M.H.C.)', 'Gerard Doulaan 2 a 1399 ES Muiderberg', false),
  ('Myra (H.V.)', 'Sportlaan 35 1185 TB Amstelveen', false),
  ('Naarden (H.C.)', 'Sportpark Naarden - Beethovenlaan 71 1411 HC Naarden', false),
  ('Never Less', 'Hazelaarweg 2 3053 PM Rotterdam', false),
  ('Nieuwegein (M.H.C.)', 'Parkhout 5 3432 NE Nieuwegein', false),
  ('Nieuwkoop (HC)', 'Dreg 1 2431 NG Nieuwkoop', false),
  ('Nijkerk (H.C.)', 'Watergoorweg 46 3861 MA Nijkerk', false),
  ('Nijmegen (N.M.H.C.)', 'd''Almarasweg 37 6525 DW Nijmegen', false),
  ('Noorderlicht', 'Volendammerweg 310 1027 EA Amsterdam', false),
  ('Noordwijkse (H.C.)', 'Nieuwe Zeeweg 40 2201 TM Noordwijk', false),
  ('Nova (H.C.)', 'Stadionbaan 38 6416 CS Heerlen', false),
  ('Nuenen (H.C.)', 'Lissevoort 8 5671 BS Nuenen', false),
  ('Nunspeet (M.H.C.)', 'Sportlaan 9 8072 BN Nunspeet', false),
  ('Nuth (H.C.)', 'Sportpark Kollenberg 1 6361 KA Nuth', false),
  ('Oedenrode, Sint (M.H.C.)', 'Bremhorst 2 5491 LR Sint-Oedenrode', false),
  ('Oirschot (H.C.)', 'Koningshof 9 a 5688 GD Oirschot', false),
  ('Olympia (M.H.C.)', 'Vliegende Vaart 15 4537 DH Terneuzen', false),
  ('Ommen (M.H.C.)', 'Sportlaan 4 7735 KX Arrien', false),
  ('Ommoordse (M.H.C.)', 'Marcel Duchampplein 810 3059 RD Rotterdam', false),
  ('Only Friends', 'Beemsterstraat 652 1027 ED Amsterdam', false),
  ('Oosterbeek (M.H.C.)', 'Sportlaan 1 6861 AG Oosterbeek', false),
  ('Oranje-Rood (HC)', 'Charles Roelslaan 7 A 5644 HX Eindhoven', false),
  ('Oss (M.H.C.)', 'Macharenseweg 14 5346 JM Oss', false),
  ('Oudenbosch (M.H.C.)', 'Albanoweg 1 a 4731 VG Oudenbosch', false),
  ('Overbetuwe (HC)', 'De Pas 2 6662 BK Elst', false),
  ('Overbos (B.H.C.)', 'van Loenenlaan 3 1945 TB Beverwijk', false),
  ('Peel en Maas (H.C.)', 'Irenestraat 61 5981 XK Panningen', false),
  ('Pelikaan, De (R.M.H.C.)', 'Heerma van Vossstraat 49 4708 AV Roosendaal', false),
  ('Phoenix (SV)', 'Koeburgweg 1 3709 JD Zeist', false),
  ('Pijnacker (H.C.)', 'Sportlaan 6 2641 AZ Pijnacker', false),
  ('PinokéJan', 'Tooroplaan 46 1182 AE Amstelveen', false),
  ('Pollux (V.M.H.C.)', 'Kooikersweg 4 3138 HE Vlaardingen', false),
  ('Prinsenbeek (H.C.)', 'Postbaan 38 4841 KL Prinsenbeek', false),
  ('Purmerend (M.H.C.)', 'Flevostraat 251 1442 PX Purmerend', false),
  ('Push (B.H.V.)', 'Nieuwe Inslag 97 4817 GN BREDA', false),
  ('PW (Prinses Wilhelmina)', 'Maatmanweg 31 7522 AN Enschede', false),
  ('Qui Vive (U.H.C.)', 'Vuurlijn 30 1424 NR De Kwakel', false),
  ('Quick Stick (H.H.C.)', 'It Hege Stik 11 8445 PZ Heerenveen', false),
  ('QZ (H.C.)', 'Staddijk-Zuid 33 6537 TW NIJMEGEN', false),
  ('Rapid (G.H.C.)', 'Bataafsekade 16 4204 AX Gorinchem', false),
  ('Rapide (M.H.C.)', 'Wittebrugstraat 6 4562 CA Hulst', false),
  ('Reeuwijk-Bodegraven (HC)', 'Reeuwijksehoutwal 1 2811 NW Reeuwijk', false),
  ('Reigers, De (M.H.C.)', 'Arnolduspark 5 2132 CR Hoofddorp', false),
  ('Rijswijksche (H.C.)', 'Lange Kleiweg 106 2288 GR Rijswijk', false),
  ('Ring Pass DelftWestblok 1', '2614 VE Delft', false),
  ('Roden (M.H.C.)', 'Roderweg 2 9301 RE Roden', false),
  ('Rood-Wit (A.M.H.C.)', 'Zwaluwenweg 11 2111 HC Aerdenhout', false),
  ('Rosmalen (M.H.C.)', 'Jos de Letterlaan 13 5248 NX Rosmalen', false),
  ('Rotterdam (H.C.)', 'Hazelaarweg 2 3053 PM Rotterdam', false),
  ('Sallandse (M.H.C.)', 'Hammerweg 16 8101 NE Raalte', false),
  ('Saxenburg (H.M.H.C.)', 'Boerhaavelaan 47 2035 RB Haarlem', false),
  ('SC Muiden', 'Maxisweg 20 1398 BT Muiden', false),
  ('Schaerweijde (Z.S.V.)', 'Hein Bottingalaan 1 3707 NX Zeist', false),
  ('SCHCKees', 'Boekelaan 1 3723 BA Bilthoven', false),
  ('Scherpenzeel (HC)', 'Eikenlaan 4 3925 VK Scherpenzeel', false),
  ('Schoonhovense (M.H.C.)', 'Prunuslaan 3 2871 RR Schoonhoven', false),
  ('Scoop (H.C.)', 'Eggerweg 5 6135 LG Sittard', false),
  ('Scoop Delft (S.H.C.)', 'Mekelweg 8 2628 CD Delft', false),
  ('SGBNoordoordplaat 24', '4465 AW Goes', false),
  ('Shinty (D.M.H.C.)', 'Hoofdstraat 21 A 3971 KA Driebergen-Rijsenburg', false),
  ('SHOT (Studenten Hockeyver. Tilburg)', 'Sportweg 13 a 5037 AC Tilburg', false),
  ('Sjinborn (V.H.V.)', 'Dr . Ariensstraat 59 6301 XH Valkenburg', false),
  ('Sneeker (M.H.C.)', 'Molenkrite 130 8608 XK Sneek', false),
  ('Soest (M.H.C.)', 'Bos straat 88 3766 AJ Soest', false),
  ('Son (H.T.C.)', 'Rooijseweg 3 5691 PA Son en Breugel', false),
  ('Souburgh (H.C.)', 'Bas Verhoevenweg 7 2952 BV Alblasserdam', false),
  ('Spaarndam (HC)', 'Zijkanaal C 11 2064 KA Spaarndam', false),
  ('Spijkenisse (H.V.)', 'Schenkelweg 110 b / 112 3203 LE Spijkenisse', false),
  ('Spitsbergen (VMHC)', 'Groeneveldselaan 9 3902 HA Veenendaal', false),
  ('Stick Flyers', 'Hoofdstraat 3 9244 CL Beetsterzwaag', false),
  ('Stix (JHC)', 'Hoge Zomerdijk 1 8501 ES Joure', false)
ON CONFLICT (name) DO UPDATE SET
  address = EXCLUDED.address
  WHERE clubs_registry.address IS NULL;

-- Totaal: 279 clubs geladen
-- Geocoördinaten: worden automatisch ingevuld bij eerste gebruik
